# ==========================================================
# Enterprise GCP Registry Allowed Values
# ==========================================================

environments:
  - sandbox
  - dev
  - test
  - uat
  - prod

businessCriticality:
  - low
  - medium
  - high
  - critical

regions:
  - europe-west1
  - europe-west2
  - europe-west3
  - europe-west4
  - us-central1
  - us-east1
  - us-east4
  - asia-south1

organizations:
  - rba

departments:
  - cloud-platform-engineering
  - finance
  - hr
  - security
  - infrastructure

projectPrefixes:
  - dev
  - test
  - prod
  - sandbox